baseURL = "/"

languageCode = "en-us"

title = "Arpit's Blog"

theme = "poison"

pluralizelisttitles = false



[pagination]

  pagerSize = 10



[params]

  brand = "Arpit's Blog"

  description = "A clean and minimal blog powered by Hugo and Poison."

  dark_mode = true



  menu = [

    {Name = "About", URL = "/about/", HasChildren = false},

    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5}

  ]



  front_page_content = ["posts"]



  github_url = "https://github.com/yourusername"

  twitter_url = "https://twitter.com/yourhandle"

  email_url = "mailto:arpit.rawat.work@gmail.com"

  linkedin_url = "https://linkedin.com/in/yourprofile"



  rss_icon = true

  rss_section = "posts"



  sidebar_bg_color = "#202020"

  sidebar_a_color = "#FFF"

  text_color = "#EEE"

  post_title_color = "#DBE2E9"



[taxonomies]

  series = "series"

  tags = "tags"


